### ISSUE TITLE
History file extension issue

### ISSUE THREAD

**Issue by koraysevinc** [bigfooted/su2tools#3]
Hi

I've just give your code a try. When I tried to open a running computation's history file, it didn't see the file. Because the running history file doesn't have an extension and your code filters the files with csv extention.

Current version of SU2 code says the following:

% Output file convergence history (w/o extension)
CONV_FILENAME= history

So, the history file is written without an extension, at least until the computation is finished.

I hope this issue will be fixed soon.
Thanks.

**Comment by bigfooted** [comment]
Hi, thanks for your report. SU2 adds the .csv extension automatically when writing the file. The type of extension depends on the keyword TABULAR_FORMAT. The default is .csv, the only other option is TECPLOT, which changes the default extension to .dat. This is why you should not add an extension in the config file. If the extension is not added then something is wrong.
Anyway, I have changed the file option so you can select "all files (*)". Monitor currently only supports comma separated values and since your extension is missing I'm not sure if your history file is written correctly.
